version: '3'

services:
  ghost:
    image: najarramsada/ghost-on-github
    container_name: ghost
    restart: always
    ports:
      - 2368:2368
    volumes:
      - ghost:/var/lib/ghost/content

volumes:
  ghost: