version: '3'

services:
  ghost:
    image: najarramsada/ghost-on-github
    container_name: ghost
    restart: always
    ports:
      - 8880:2368
    volumes:
      - ghost:/home/node/.ghost/content

volumes:
  ghost: